### ISSUE TITLE
module already registered: caddy.listeners.proxy_protocol

### ISSUE THREAD

**Issue by lambdaxyzt** [mastercactapus/caddy2-proxyprotocol#17]
Hi, I download caddy with this "2Fmastercactapus/caddy2-proxyprotocol" plugin but get weird error !

https://caddyserver.com/api/download?os=windows&arch=amd64&p=github.com%2Fmastercactapus%2Fcaddy2-proxyprotocol

```
panic: module already registered: caddy.listeners.proxy_protocol

goroutine 1 [running]:
github.com/caddyserver/caddy/v2.RegisterModule({0x1e65a40?, 0xc000235d00?})
        github.com/caddyserver/caddy/v2@v2.8.4/modules.go:156 +0x1dd
github.com/mastercactapus/caddy2-proxyprotocol.init.0()
        github.com/mastercactapus/caddy2-proxyprotocol@v0.0.2/caddy.go:9 +0x46
```

**Comment by francislavoie** [comment]
Yeah you no longer need this plugin at all, it's now built into Caddy.

**Comment by lambdaxyzt** [comment]
Son when i see it in docs , it means it has built in ! Tnx
